### ISSUE TITLE
Please provide am MySQL Demo-Database-Dump

### ISSUE THREAD

**Issue by gunnarhaslinger** [openprovider/whoisd#5]
@takama 
Dear Igor,
Would be really helpful, if you can provide a MySQL Demo-Database-Dump (+ eventually the corresponding mapping.json File).

**Comment by gunnarhaslinger** [comment]
OK, figured out how to do it with mysql.

**Comment by takama** [comment]
@gunnarhaslinger 
Dear Gunnar, sorry for my late response. I didn't develop mysql module, it was contributed by community. If your issue is actual I will try to make the dump. We used ElasticSearch.
